apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpg-ia-backend
  labels:
    app: rpg-ia-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rpg-ia-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rpg-ia-backend
    spec:
      containers:
      - name: rpg-ia-backend
        image: rpg-ia-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: ENV
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: API_PORT
        - name: LLM_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: LLM_ENDPOINT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rpg-ia-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rpg-ia-secrets
              key: POSTGRES_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rpg-ia-secrets
              key: SECRET_KEY
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: ALGORITHM
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: rpg-ia-config
              key: REDIS_URL
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: rpg-ia-secrets
              key: OPENROUTER_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rpg-ia-secrets
              key: OPENAI_API_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
      restartPolicy: Always